tracer:
  property: "I AM THE DEVELOPER"
example:
  property: "This is a example custom property"
spring:
  jpa:
    hibernate:
      ddl-auto: "update"
    database: "mysql"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/dev"
    username: "root"
    password: "1234"
