tracer:
  property: "I AM THE DEVELOPER"
spring:
  jpa:
    hibernate:
      ddl-auto: "update"
    database: "mysql"
  datasource:
    url: "jdbc:mysql://localhost:3306/dev"
    username: "root"
    password: "1234"
